### ISSUE TITLE
!

### ISSUE THREAD

**Issue by jiggaaut** [qwerti1010/Accounting#2]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Repositories/ComputerRep.cs#L29

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Repositories/EmployeeRep.cs#L64
["id"] ?

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Repositories/ComputerRep.cs#L73
единообразно бы

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Repositories/EmployeeRep.cs#L98
нужен close и dispose до return

**Comment by jiggaaut** [comment]
У проекта (!!) Accounting сломаны зависимости

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/LoginForm.cs#L32
dbContext тоже можно прокинуть

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/LoginForm.cs#L21
is null достаточно

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Repositories/IRepository.cs#L9
в реализациях нет nullable

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Computer.cs#L22
bool

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/ComputerForm.cs#L134-L148
Не так. В комбобоксах должны быть все юзеры/места/статусы чтобы можно было поменять у устройства на другое,
и прикрепить к устройству можно только 1го юзера/место/статус, листы не нужны

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/ComputerForm.cs#L7
nullable

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/MainForm.cs#L261
var form = new ComputerForm(null, _computers); и второй конструктор не нужен

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/MainForm.cs#L56-L65
будем доставать только первые 10

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/WinForms/MainForm.cs#L282-L293
фильтровать нужно из бд

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Computer.cs#L10
EmployeeID

https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Computer.cs#L9
Status byte - в коде должна быть enum-расшифровка

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/c0ee37152ddc52ab96973fccc8262c492089460c/DBLibrary/Computer.cs#L5
не пон, в репах у тебя computerid первичный ключ? Поменяй на ID если так

**Comment by qwerti1010** [comment]
1
