### ISSUE TITLE
Исправления

### ISSUE THREAD

**Issue by jiggaaut** [qwerti1010/Accounting#3]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/Accounting.csproj#L11-L13
не нужно

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/DbContext.cs#L5
IDisposable

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/Repositories/ComputerRep.cs#L17
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/Repositories/EmployeeRep.cs#L17
убрать метод, skip take перенести в Filter

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/MainForm.cs#L82-L92
can be null

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/MainForm.cs#L300
ToList не нужен

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/MainForm.cs#L253
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/MainForm.cs#L263
SelectedIndex сравнивается с магическими цифрами - в переменки

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/ComputerForm.cs#L32-L38
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/ComputerForm.cs#L92-L95
Всегда false

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/ComputerForm.cs#L96-L99
А если null?

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/Interfaces/IEmployeeRepository.cs#L8
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/Repositories/EmployeeRep.cs#L110
Непорядок

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/Repositories/ComputerRep.cs#L37

public interface IEmployeeRepository
public List<Employee> GetEmployees(string name, string phone, string? login = null); - C# 8 +
List<Employee> GetEmployees(string name, string phone, string login = null); - C# 7.3

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/ComputerForm.cs#L143
Это работает?

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/WinForms/Accounting.csproj#L6
Nullable>enable /Nullable>

**Comment by jiggaaut** [comment]
https://github.com/qwerti1010/Accounting/blob/28ee9dabf3ea31516b1b7b9767c9c0d99c68ec60/DBLibrary/Repositories/ComputerRep.cs#L103
LAST_INSERT_ID()

**Comment by qwerti1010** [comment]
1
